name: Scheduled CI with Gradle

on:
  schedule:
    - cron: '30 12 * * 3'  
    - cron: '0 22 * * 5'   
permissions:
  contents: read
jobs:
  gradle:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        jdk: [8, 11, 17]
    runs-on: ${{ matrix.os }}
    env:
      JDK_VERSION: ${{ matrix.jdk }}
    steps:
      - name: checkout Repo
        uses: actions/checkout@v3
      - name: setup gradle
        uses: gradle/gradle-build-action@v2
      - name: Change wrapper premission
        run: chmod +x ./gradlew
      - name: Build with Gradle
        run: ./gradlew build
      
